<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="Pooja-17125" failures="1" tests="2" name="Default test(failed)" time="0.064" errors="0" timestamp="04 Apr 2020 07:24:49 GMT">
  <testcase classname="PriorityDemo.TestNGRetryFailedDemo" name="test3" time="0.016">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at PriorityDemo.TestNGRetryFailedDemo.test3(TestNGRetryFailedDemo.java:25)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase classname="PriorityDemo.TestNGRetryFailedDemo" name="test2" time="0.001"/>
  <testcase classname="PriorityDemo.TestNGRetryFailedDemo" name="test1" time="0.0">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- Default test(failed) -->
